name: Update Certificate

on: 
  workflow_dispatch:
  schedule:
    # Run every Wednesday at midnight
    - cron: 0 0 * * WED

jobs:
  update-cert:
    runs-on: ubuntu-latest
    env: 
      ocaml-compiler: "5.1"
    steps:
    - name: Checkout tree
      uses: actions/checkout@v4

    - name: Download and compare latest certificate
      id: check_changes
      continue-on-error: true
      shell: bash
      run: |
        current=$(cat cacert.pem | sha256sum)
        ./download_pem.sh
        latest=$(cat cacert.pem | sha256sum)
        if [ "$current" = "$latest" ]; then
          echo "No changes to cacert.pem. Skipping build!"
          exit 1
        fi

    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      if: steps.check_changes.outcome == 'success'
      with:
        ocaml-compiler: ${{ env.ocaml-compiler }}

    - name: Install OCaml deps
      if: steps.check_changes.outcome == 'success'
      run: |
        opam install castore x509 ca-certs cstruct mdx ocamlformat dune-release
        opam exec -- dune build
        ./_build/default/regen.exe
        opam exec -- dune fmt || true

    - name: Bump version and create release
      if: steps.check_changes.outcome == 'success'
      shell: bash
      run: |
        git pull --tags --force
        current_version=$(git describe --tags $(git rev-list --tags --max-count=1))
        IFS='.' read -r major minor patch <<< "$current_version"
        new_version="$major.$minor.$((patch + 1))"

        opam exec -- dune-release tag "$new_version"
        opam exec -- dune-release distrib
        opam exec -- dune-release publish distrib -y
        opam exec -- dune-release opam pkg
        opam exec -- dune-release opam submit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
